<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>
</head>
<body>
    <h1>Добро пожаловать на страницу, Админ</h1>
    <a href="/adminPage/addAdmin">Админ</a>
    <a href="/adminPage/addTeacher">Учитель</a>
    <a href="/adminPage/addStudent">Студент</a>
    <a href="/adminPage/addComment">Комментарии</a>
    <a href="/adminPage/addFile">Файл</a>
    <a href="/adminPage/addSubject">Предмет</a>

</body>
</html>