<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ChangePassword</title>
</head>
<body>
    <form action="changePassword" method="post">
        <input type="password" name="password" placeholder="Введите пароль">
        <input type="password" name="repeatedPassword" placeholder="Повторите пароль">
        <button type="submit" value="Сменить пароль">Сменить пароль</button>
    </form>
</body>
</html>