<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/css/homePage.css" rel="stylesheet" >
    <title>Home</title>
</head>
<header>
    <div class="header">
        <a class="link" href="/account">Личный кабинет</a>
        <a class="link" href="/user/home/">Главная</a>
        <a class="link" href="/teachers">Найти учителя</a>
        <a class="link" href="/sendCode">Сменить пароль</a>
        <img class="img" src="/images/${avatarSrc}" alt="Фото">
    </div>
</header>
<body>

</body>
</html>